### ISSUE TITLE
some suggestions

### ISSUE THREAD

**Issue by steve02081504** [Zichqec/s-the-skeleton#1]
Here are some suggestions for the content of this page: https://zichqec.github.io/s-the-skeleton/github.html

With [.gitignore](https://git-scm.com/docs/gitignore) files, you can decide files in track for your git repository
By using the [developer_options.txt](http://ssp.shillest.net/ukadoc/manual/descript_install.html#developer_options.txt) file, you can decide which files are used to make update or NAR files
You don't need to delete any files. Your ghost directory can be used to run ghost、make their updates and NARs、act as a git repository at the same time

As for making update or NAR files, I personally recommend using the [`\![open,ghostexplorer]`](http://ssp.shillest.net/ukadoc/manual/list_sakura_script.html#_!_open,ghostexplorer_)UI to operate, and it's not hard to add a 'ghost explorer' item in the ghost‘s menu
It's better than dragging a folder,I think,since some ghost will define [OnFileDropEx](http://ssp.shillest.net/ukadoc/manual/list_shiori_event.html#OnFileDropEx)、[OnFileDrop](http://ssp.shillest.net/ukadoc/manual/list_shiori_event.html#OnFileDrop)、[OnFileDrop2](http://ssp.shillest.net/ukadoc/manual/list_shiori_event.html#OnFileDrop2), which makes dragging and dropping a folder not always useful

**Comment by Zichqec** [comment]
Thank you for the suggestions! I hadn't considered using developer_options.txt before, I will definitely add a note about that at some point, when I have a chance to update this guide.

Unfortunately, I think only a handful of people in the english ukagaka community even _know_ about the ghost explorer. However, if you have developer mode turned on in SSP, dragging and dropping a folder with an install.txt file in it will not activate the OnFileDrop events unless you specifically tell it to. So, I don't believe this is an issue. Still, maybe I should make a note of the ghost explorer, to introduce it to more people. It seems like a handy tool, if only more folks knew about it.
